### ISSUE TITLE
Proposal peer review

### ISSUE THREAD

**Issue by tezz-us** [INFO523-S24/project-01-Seasons-Screenings#1]
The following is the peer review of the project proposal by [name of team completing peer review]. The team members that participated in this review are 

-  Ayesha Khatun - @ayeshakhatunsujana
-  Alyssa Nether - @rlyalyther
-  Akash Srinivasan - @AkashSrinivasan12
-  Tejas Bhawari -  @tezz-us
-  Gabriel Geffen - @gabegef

- Describe the goal of the project.
Utilizing the Holiday Movies dataset and the IMDB API, Season's Screenings aim is to analyze trends in features of popular movies and ultimately search for correlations between movie that performed well and had high earnings. The first goal will be to filter movies with the highest ratings (top 50th percentile) and see how the genre popularity, movie duration and title length has changed over time. After this, they will use the aforementioned movie features, as well as production year and ratings, to estimate the box office performance of a movie.

- Describe the data used or collected.
The Holiday Movies dataset explores films related to various holiday types, spanning genres, average rating, years, and runtime. It examines popularity, genre distribution, and temporal trends, offering insights into the evolution of holiday movies evolving in terms of genres, duration and audience reception.

- Describe how the research question will be answered, e.g. what approaches / methods will be used.
First they will create a few new columns that include calculating the length of each movie title by their character count, categorizing each move based on which quartile their movie rating lies in, and the number of genres per each movie. Following this, the authors state that they will remove rows that contain missing data or outliers. For their specific trend analysis, it is somewhat unclear how they  plan on performing these analyses, but it seems like they will make four plots or analyses to determine the most common genre among holiday movies, the preferred movie length of the more popular movies, the length of movie title and their ratings, and the change in average movie ratings over time.they will be doing 5 different comparisons between earnings and the rest of the variables (time, genre, duration, title length, rating and release year). all comparisons will be seeing if changing variables will lead to higher earnings.

- Is there anything that is unclear from the proposal?
Neglected to include a common project introduction in the application's description. Could you perhaps explain why they selected this dataset? The question's response can be more precise. To help with the objective and intention of the project, they should include an introduction and discussion for each question. Which algorithms, such as regression, are absent from the question's Analysis section?

- Provide constructive feedback on how the team might be able to improve their project.
To enhance this project including more data set with IMDb’s rating and financial reports would definitely add on to the visual representations.Building graphs considering ‘Holiday’ column which basically has a constant value ’True’ won’t affect the visualization much rather than considering the following column. Adding external data of how external factors such as economic conditions, cultural trends, or competitor releases influence the performance of holiday movies. Incorporating external variables can enrich the analysis and provide a broader context and also the audience based on demographics, preferences, or viewing behaviors to identify niche markets or target audiences for holiday movies.The dataset description seems to focus on how this dataset discusses holidays and has an overall theme of "holiday season". However, in reading through the analysis, it seems like this doesn't have anything to do with their objectives and questions. It might be good to add a sentence to keep the overall format consistent.

- What aspect of this project are you most interested in and would like to see highlighted in the presentation.
1.To see what direction the holiday movie genres are progressing towards
2.interested to see if the length of movie title actually has an impact during analysis

- Provide constructive feedback on any issues with file and/or code organization.
The holiday_movies.csv file was loaded into the proposal.qmd file, however it is also possible to print it here to make it easier to understand their dataset and variables. If the data cleansing portion's code is published on github, they can add it.In addition, there are some columns and variables that are not intuitively understood. After displaying the head of the data, there should be some description of why the there is a title and simple title column, or what "tconst" actually means.

- (Optional) Any further comments or feedback?
1. add a ' : ' after 'Let us look at the shape of the data'
2. misspelled production in the description of Q2 under the 'questions' section
3. try not to use all variables for both Q1 and Q2.. there is a lot of overlap between these and maybe try to make it somewhat different.
4. the data prep area for both Q1 and Q2 are messy.. make it a table because I am see lots of ' : ' with descriptions but it is not clean (edited)

**Comment by RAJITHAREDDYTIRUTHANI** [comment]
Thank you for the feedback 
"Provide constructive feedback on any issues with file and/or code organization." 

         "However it is also possible to print it here to make it easier to understand their dataset and variables"
You can refer to the README.md file as it looks clumsy to explain variable in the proposal.
As mentioned about "what does tconst" it is nothing but a unique idendtifier of the title
"simple_title" it means the title in lowercase, with punctuation removed, for easier filtering and grouping
.

**Comment by suryavardhandama** [comment]
We appreciate you taking the time to look over our project proposal and for your informative and helpful criticism. We greatly appreciate your recommendations for determining the influence of external variables. We have done all the necessary things and updated our proposal and any extra information required will be taken using IMDb's API.

Thank You

Best Regards
Seasons-Screenings
