### ISSUE TITLE
Proposal peer review from Algo Aces

### ISSUE THREAD

**Issue by tanyageorge** [INFO523-S24/project-01-Seasons-Screenings#2]
The following is the peer review of the project proposal by [name of team completing peer review]. The team members that participated in this review are 

- Tanya Evita George - @tanyageorge
- Valerie Okine - @valerie-okine
- Sai Navya Reddy Busireddy - @navyareddy152
- Monica Tejaswi Kommareddy - @KommareddyMonicatejaswi
- Gowtham Theeda - @gowthamtheeda

- Describe the goal of the project.
The goal of the project is to research trends of popular movies during holiday season. It also includes looking at any correlations between movie features and their box office earnings. 

- Describe the data used or collected.
The dataset gives information on the different movies,  titles ,genres, year they were released, runtime duration, average rating, number of votes the movie got on IMDb.

- Describe how the research question will be answered, e.g. what approaches / methods will be used.

In question 1, research is done on the average ratings of movies and will be analysed on how much the movies have evolved in terms of genre, duration and titles. 
In question 2, the questions will be answered by studying the correlations between the movie features. A model will be a created to estimate how worthy a movie is in terms of investment.

- Is there anything that is unclear from the proposal?

It is unclear on what type of visualization method or plots will be used for the analysis of the dataset.  It is also unclear what the exact questions are. Only descriptions of the questions were given.

- Provide constructive feedback on how the team might be able to improve their project.

1. Both the question 1 and 2 are not framed as questions but rather explanations of the analysis plan of the project. Please frame straightforward and direct questions that can be easily understood.
2. Please give brief descriptions about the variables used so we know what they mean. For example: 'num_votes', could not understand what it meant.

- What aspect of this project are you most interested in and would like to see highlighted in the presentation.

1. Looking forward to finding out which genre of movie is the most poplar as well as most underrated. 
2. Which holiday movies earned the most in the box office. (so we could watch/rewatch them.)
3.  How the movies with the higher ratings fare in the box office compared to those with the lower ratings.

- Provide constructive feedback on any issues with file and/or code organization.

The file organization seems fine. Not much code to analyze on the website.

- (Optional) Any further comments or feedback?

**Comment by h-akston** [comment]
Thank you for the feedback! I have managed to identify three main issues that you raise in your review:

1. "It is unclear on what type of visualization method or plots will be used". At the current stage, it is hard and may be even unwise to predetermine the types of visualization plots to be used. We would rather try to pick the most appropriate techniques depending on the kind of data we get as the result of our analysis.
2. "It is also unclear what the exact questions are". The proposal has been modified to include clear and simple question first, only then followed by more detailed explanations of those questions.
3. "give brief descriptions about the variables used". Please refer to /data/README.md within our project's repository, it contains descriptions of all variables used in the dataset.
